import Link from "next/link"
import "../globals.css"
import Navbar from "@/components/NavBar"
export const revalidate = 30

export const metadata = {
	title: "Victor Manuel",
	description: "Generated by victor manuel",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className='w-full h-screen font-bodyFont  overflow-x-hidden overflow-y-scroll'>
				<header>
					<Navbar />
				</header>
				{children}
			</body>
		</html>
	)
}
